
from helpner.download import _get_wheel

response = [
  {
    "url": "https://api.github.com/repos/plaguss/helpner-core/releases/91294063",
    "assets_url": "https://api.github.com/repos/plaguss/helpner-core/releases/91294063/assets",
    "upload_url": "https://uploads.github.com/repos/plaguss/helpner-core/releases/91294063/assets{?name,label}",
    "html_url": "https://github.com/plaguss/helpner-core/releases/tag/v0.2.0",
    "id": 91294063,
    "author": {
      "login": "plaguss",
      "id": 56895847,
      "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/plaguss",
      "html_url": "https://github.com/plaguss",
      "followers_url": "https://api.github.com/users/plaguss/followers",
      "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
      "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
      "organizations_url": "https://api.github.com/users/plaguss/orgs",
      "repos_url": "https://api.github.com/users/plaguss/repos",
      "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/plaguss/received_events",
      "type": "User",
      "site_admin": False
    },
    "node_id": "RE_kwDOIsRRC84FcQlv",
    "tag_name": "v0.2.0",
    "target_commitish": "main",
    "name": "en_helpner_core-0.2.0",
    "draft": False,
    "prerelease": False,
    "created_at": "2023-02-03T16:58:53Z",
    "published_at": "2023-02-03T17:04:04Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/plaguss/helpner-core/releases/assets/94202261",
        "id": 94202261,
        "node_id": "RA_kwDOIsRRC84FnWmV",
        "name": "en_helpner_core-0.2.0-py3-none-any.whl",
        "label": None,
        "uploader": {
          "login": "plaguss",
          "id": 56895847,
          "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
          "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/plaguss",
          "html_url": "https://github.com/plaguss",
          "followers_url": "https://api.github.com/users/plaguss/followers",
          "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
          "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
          "organizations_url": "https://api.github.com/users/plaguss/orgs",
          "repos_url": "https://api.github.com/users/plaguss/repos",
          "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
          "received_events_url": "https://api.github.com/users/plaguss/received_events",
          "type": "User",
          "site_admin": False
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 6231490,
        "download_count": 3,
        "created_at": "2023-02-03T17:03:09Z",
        "updated_at": "2023-02-03T17:03:24Z",
        "browser_download_url": "https://github.com/plaguss/helpner-core/releases/download/v0.2.0/en_helpner_core-0.2.0-py3-none-any.whl"
      },
      {
        "url": "https://api.github.com/repos/plaguss/helpner-core/releases/assets/94202211",
        "id": 94202211,
        "node_id": "RA_kwDOIsRRC84FnWlj",
        "name": "en_helpner_core-0.2.0.tar.gz",
        "label": None,
        "uploader": {
          "login": "plaguss",
          "id": 56895847,
          "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
          "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/plaguss",
          "html_url": "https://github.com/plaguss",
          "followers_url": "https://api.github.com/users/plaguss/followers",
          "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
          "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
          "organizations_url": "https://api.github.com/users/plaguss/orgs",
          "repos_url": "https://api.github.com/users/plaguss/repos",
          "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
          "received_events_url": "https://api.github.com/users/plaguss/received_events",
          "type": "User",
          "site_admin": False
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 6231410,
        "download_count": 0,
        "created_at": "2023-02-03T17:02:33Z",
        "updated_at": "2023-02-03T17:03:09Z",
        "browser_download_url": "https://github.com/plaguss/helpner-core/releases/download/v0.2.0/en_helpner_core-0.2.0.tar.gz"
      }
    ],
    "tarball_url": "https://api.github.com/repos/plaguss/helpner-core/tarball/v0.2.0",
    "zipball_url": "https://api.github.com/repos/plaguss/helpner-core/zipball/v0.2.0",
    "body": "| Feature | Description |\r\n| --- | --- |\r\n| **Name** | `en_helpner_core` |\r\n| **Version** | `0.2.0` |\r\n| **spaCy** | `>=3.5.0,<3.6.0` |\r\n| **Default Pipeline** | `tok2vec`, `ner` |\r\n| **Components** | `tok2vec`, `ner` |\r\n| **Vectors** | 0 keys, 0 unique vectors (0 dimensions) |\r\n| **Sources** | n/a |\r\n| **License** | n/a |\r\n| **Author** | [n/a]() |\r\n\r\n### Label Scheme\r\n\r\n<details>\r\n\r\n<summary>View label scheme (3 labels for 1 components)</summary>\r\n\r\n| Component | Labels |\r\n| --- | --- |\r\n| **`ner`** | `ARG`, `CMD`, `OPT` |\r\n\r\n</details>\r\n\r\n### Accuracy\r\n\r\n| Type | Score |\r\n| --- | --- |\r\n| `ENTS_F` | 96.72 |\r\n| `ENTS_P` | 97.23 |\r\n| `ENTS_R` | 96.21 |\r\n| `TOK2VEC_LOSS` | 59804.53 |\r\n| `NER_LOSS` | 40418.24 |\r\n\r\nModel version according to the following [dataset.yaml](https://github.com/plaguss/helpner-core/blob/main/assets/v0.2.0/dataset.yaml)"
  },
  {
    "url": "https://api.github.com/repos/plaguss/helpner-core/releases/90346559",
    "assets_url": "https://api.github.com/repos/plaguss/helpner-core/releases/90346559/assets",
    "upload_url": "https://uploads.github.com/repos/plaguss/helpner-core/releases/90346559/assets{?name,label}",
    "html_url": "https://github.com/plaguss/helpner-core/releases/tag/v0.1.3",
    "id": 90346559,
    "author": {
      "login": "plaguss",
      "id": 56895847,
      "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/plaguss",
      "html_url": "https://github.com/plaguss",
      "followers_url": "https://api.github.com/users/plaguss/followers",
      "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
      "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
      "organizations_url": "https://api.github.com/users/plaguss/orgs",
      "repos_url": "https://api.github.com/users/plaguss/repos",
      "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/plaguss/received_events",
      "type": "User",
      "site_admin": False
    },
    "node_id": "RE_kwDOIsRRC84FYpQ_",
    "tag_name": "v0.1.3",
    "target_commitish": "main",
    "name": "en_helpner_core-0.1.3",
    "draft": False,
    "prerelease": False,
    "created_at": "2023-01-26T19:52:16Z",
    "published_at": "2023-01-26T20:25:28Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/plaguss/helpner-core/releases/assets/93158977",
        "id": 93158977,
        "node_id": "RA_kwDOIsRRC84FjX5B",
        "name": "en_helpner_core-0.1.3-py3-none-any.whl",
        "label": None,
        "uploader": {
          "login": "plaguss",
          "id": 56895847,
          "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
          "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/plaguss",
          "html_url": "https://github.com/plaguss",
          "followers_url": "https://api.github.com/users/plaguss/followers",
          "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
          "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
          "organizations_url": "https://api.github.com/users/plaguss/orgs",
          "repos_url": "https://api.github.com/users/plaguss/repos",
          "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
          "received_events_url": "https://api.github.com/users/plaguss/received_events",
          "type": "User",
          "site_admin": False
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 5706796,
        "download_count": 5,
        "created_at": "2023-01-26T19:56:13Z",
        "updated_at": "2023-01-26T19:56:17Z",
        "browser_download_url": "https://github.com/plaguss/helpner-core/releases/download/v0.1.3/en_helpner_core-0.1.3-py3-none-any.whl"
      },
      {
        "url": "https://api.github.com/repos/plaguss/helpner-core/releases/assets/93158970",
        "id": 93158970,
        "node_id": "RA_kwDOIsRRC84FjX46",
        "name": "en_helpner_core-0.1.3.tar.gz",
        "label": None,
        "uploader": {
          "login": "plaguss",
          "id": 56895847,
          "node_id": "MDQ6VXNlcjU2ODk1ODQ3",
          "avatar_url": "https://avatars.githubusercontent.com/u/56895847?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/plaguss",
          "html_url": "https://github.com/plaguss",
          "followers_url": "https://api.github.com/users/plaguss/followers",
          "following_url": "https://api.github.com/users/plaguss/following{/other_user}",
          "gists_url": "https://api.github.com/users/plaguss/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/plaguss/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/plaguss/subscriptions",
          "organizations_url": "https://api.github.com/users/plaguss/orgs",
          "repos_url": "https://api.github.com/users/plaguss/repos",
          "events_url": "https://api.github.com/users/plaguss/events{/privacy}",
          "received_events_url": "https://api.github.com/users/plaguss/received_events",
          "type": "User",
          "site_admin": False
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 5706703,
        "download_count": 0,
        "created_at": "2023-01-26T19:56:04Z",
        "updated_at": "2023-01-26T19:56:13Z",
        "browser_download_url": "https://github.com/plaguss/helpner-core/releases/download/v0.1.3/en_helpner_core-0.1.3.tar.gz"
      }
    ],
    "tarball_url": "https://api.github.com/repos/plaguss/helpner-core/tarball/v0.1.3",
    "zipball_url": "https://api.github.com/repos/plaguss/helpner-core/zipball/v0.1.3",
    "body": "| Feature | Description |\r\n| --- | --- |\r\n| **Name** | `en_helpner_core` |\r\n| **Version** | `0.1.3` |\r\n| **spaCy** | `>=3.5.0,<3.6.0` |\r\n| **Default Pipeline** | `tok2vec`, `ner` |\r\n| **Components** | `tok2vec`, `ner` |\r\n| **Vectors** | 0 keys, 0 unique vectors (0 dimensions) |\r\n| **Sources** | n/a |\r\n| **License** | n/a |\r\n| **Author** | [n/a]() |\r\n\r\n### Label Scheme\r\n\r\n<details>\r\n\r\n<summary>View label scheme (3 labels for 1 components)</summary>\r\n\r\n| Component | Labels |\r\n| --- | --- |\r\n| **`ner`** | `ARG`, `CMD`, `OPT` |\r\n\r\n</details>\r\n\r\n### Accuracy\r\n\r\n| Type | Score |\r\n| --- | --- |\r\n| `ENTS_F` | 98.36 |\r\n| `ENTS_P` | 100.00 |\r\n| `ENTS_R` | 96.77 |\r\n| `TOK2VEC_LOSS` | 19373.08 |\r\n| `NER_LOSS` | 3442.93 |\r\n\r\nModel version according to the following [dataset.yaml](https://github.com/plaguss/helpner-core/blob/main/assets/v0.1.3/dataset.yaml)."
  },
]


def test_get_wheel():
    assert "https://github.com/plaguss/helpner-core/releases/download/v0.2.0/en_helpner_core-0.2.0-py3-none-any.whl" == _get_wheel(response)
